// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Zgm6MwnBt3YLxE1VX5ME0vV7qP-gZc4',
    appId: '1:952360999509:web:c8a5ba9259e7e60a9e12dc',
    messagingSenderId: '952360999509',
    projectId: 'finanlearn',
    authDomain: 'finanlearn.firebaseapp.com',
    storageBucket: 'finanlearn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHDpugnG3oALNOFsuqSg4Fo0LViN82yUI',
    appId: '1:952360999509:android:4cf820bccf2703729e12dc',
    messagingSenderId: '952360999509',
    projectId: 'finanlearn',
    storageBucket: 'finanlearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOIyUhWeQltWdgOXlDTtuUwc67ceRKC2o',
    appId: '1:952360999509:ios:bc7d78611fb087979e12dc',
    messagingSenderId: '952360999509',
    projectId: 'finanlearn',
    storageBucket: 'finanlearn.appspot.com',
    iosBundleId: 'com.example.finanlearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOIyUhWeQltWdgOXlDTtuUwc67ceRKC2o',
    appId: '1:952360999509:ios:a6253848704449cb9e12dc',
    messagingSenderId: '952360999509',
    projectId: 'finanlearn',
    storageBucket: 'finanlearn.appspot.com',
    iosBundleId: 'com.example.finanlearn.RunnerTests',
  );
}
